# Generated by Django 3.1.5 on 2021-01-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام شرکت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='آدرس اینترنتی شرکت')),
                ('about', models.TextField(verbose_name='درباره شرکت')),
                ('cover', models.ImageField(upload_to='media', verbose_name='عکس شرکت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به روز شده')),
                ('founder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('staff', models.ManyToManyField(to='staff.Staff', verbose_name='کارکنان')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
                'ordering': ['name'],
            },
        ),
    ]
