# Generated by Django 3.1.5 on 2021-01-22 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_auto_20210122_1501'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Fcompany', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(related_name='Scompany', to='staff.Staff', verbose_name='کارکنان'),
        ),
    ]
