# Generated by Django 3.1.5 on 2021-01-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='نام')),
                ('last_name', models.CharField(max_length=15, verbose_name='نام خانوادگی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='عکس پروفایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره کارمند')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به روز شده')),
                ('job', models.CharField(choices=[('staf', 'کارمند'), ('send', 'مدیر محصول'), ('plan', 'حسابدار')], max_length=4, verbose_name='سمت')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume', verbose_name='رزومه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['last_name'],
            },
        ),
    ]
