# Generated by Django 3.1.5 on 2021-01-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210122_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
